version: '3.5'
services:
  brain-ag-api:
    build:
      context: .
    volumes:
      - .:/app  
      - /app/node_modules
    ports:
      - "3001:3001"
    networks:
      - nestjs_network     
    depends_on:
      - brain-ag-db

  brain-ag-db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5433:${DATABASE_PORT}"   
    networks:
      - nestjs_network  

networks:
  nestjs_network:
    driver: bridge