version: '3.5'
services:
  brain-ag-api:
    build:
      context: .
    volumes:
      - .:/app  
      - /app/node_modules
    ports:
      - "3001:3001"
    networks:
      - nestjs_network     
    depends_on:
      - brain-ag-db

  brain-ag-db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./.docker/db:/docker-entrypoint-initdb.d # Volume para o script SQL
      - ./.docker/db/pgdata:/var/lib/postgresql/data  
    ports:
      - "5433:${DATABASE_PORT}"   
    networks:
      - nestjs_network  

  otel-collector:
      image: otel/opentelemetry-collector-contrib:latest
      volumes:
        - ./otel-collector-config.yml:/etc/otel-collector-config.yml
      command:
        - "--config=/etc/otel-collector-config.yml"
      ports:
        - "4317:4317"  # Porta para OTLP gRPC
        - "4318:4318"  # Porta para OTLP HTTP
      networks:
        - nestjs_network  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686'  # Interface do Jaeger
      - '4319:4317'  # Porta de coleta de traços         
    networks:
      - nestjs_network        

networks:
  nestjs_network:
    driver: bridge